HW10 is completed
filatkinen/hw-test pull request #10
Opened 2023-05-07 15:10 UTC by filatkinen

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

benchstat:
oos: linux
goarch: amd64
pkg: github.com/filatkinen/hw-test/hw10_program_optimization
cpu: AMD Ryzen 7 5800H with Radeon Graphics
                        │     old.txt       │               new.txt               │
                        │     sec/op      │   sec/op     vs base          │
GetDomainStatRecords-16   119301.61µ ± 7%   11.67µ ± 7%  -99.99% (p=0.000 n=10)

                        │      old.txt      │                new.txt                │
                        │       B/op       │     B/op      vs base             │
GetDomainStatRecords-16   132857.259Ki ± 0%   6.148Ki ± 0%  -100.00% (p=0.000 n=10)

                        │     old.txt     │               new.txt               │
                        │    allocs/op    │ allocs/op   vs base                 │
GetDomainStatRecords-16   1700080.00 ± 0%   45.00 ± 0%  -100.00% (p=0.000 n=10)

2023-05-07 15:51 UTC, dshemin requested changes

2023-05-07 15:51 UTC, dshemin commented on hw10_program_optimization/stats.go
> +	go func() {
Важно:

Вы добавили канал, но у нас он обрабатывается в один поток. В итоге не получаем не самое оптимальное решение. Надо либо заспавнить несколько горутин, которые будут обрабатывать этот канал, либо обрабатывать всё в один цикл.

2023-05-07 15:51 UTC, dshemin commented on hw10_program_optimization/stats.go
> +			log.Printf("error unmarshaling string number=%d, error=%s", loop, user.err)
Важно:

Мы залогировали ошибку и продолжили выполнять код дальше в котором мы работаем со значением пользователя, которое будет пустым. Лучше сдесь добавить continue.

2023-05-07 15:51 UTC, dshemin commented on hw10_program_optimization/stats.go
> +		for i := 0; i < lendomain; i++ {
Важно:

Слишком усложнёный код, можно проще.

2023-05-07 15:51 UTC, dshemin commented on hw10_program_optimization/stats_test.go
> +func BenchmarkGetDomainStatFile(b *testing.B) {
Важно:

Бенчмарк в пайплайне гитхаба не рассчитан на то, что вы будет разархивировать и обрабатывать 5 мб  данных.

2023-05-07 20:42 UTC, filatkinen commented on hw10_program_optimization/stats.go
> +	go func() {
Добваил каналы

2023-05-07 20:42 UTC, filatkinen commented on hw10_program_optimization/stats.go
> +			log.Printf("error unmarshaling string number=%d, error=%s", loop, user.err)
Добавил continue

2023-05-07 20:42 UTC, filatkinen commented on hw10_program_optimization/stats.go
> +		for i := 0; i < lendomain; i++ {
Упростил

2023-05-07 20:56 UTC, filatkinen commented on hw10_program_optimization/stats_test.go
> +func BenchmarkGetDomainStatFile(b *testing.B) {
Убрал, добавил вместо него дополнительный тест

2023-05-08 07:42 UTC, dshemin approved these changes

2023-05-08 07:46 UTC, merged