HW11 is completed
filatkinen/hw-test pull request #11
Opened 2023-05-10 08:20 UTC by filatkinen

## Домашнее задание №11 «Клиент TELNET»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2023-05-10 17:45 UTC, dshemin requested changes

2023-05-10 17:45 UTC, dshemin commented on hw11_telnet_client/main.go
> +	scanner := bufio.NewScanner(os.Stdin)
Важно:

Сейчас у нас получается так: мы оборачиваем входной поток в сканер, читаем из сканера построчно и пишем в буфер. Далее вы берём этот буфер, оборачиваем его в сканер и читаем построчно. Зачем так сложно? Можно просто читать из входного потока и отправлять в клиента. Более того, этот самый клиент будет читать этот буфер сразу же после того, как мы в него запишем.

2023-05-10 17:45 UTC, dshemin commented on hw11_telnet_client/main.go
> +	defer wg.Done()
Важно:

Не добавляйте WaitGroup как аргумент функции. Она не нужна для работы кода внутри и только добавляет зависимость. Что будем делать если нам в другом месте понадобится этот же код, но синхронно?

2023-05-10 17:45 UTC, dshemin commented on hw11_telnet_client/main.go
> +		receiveRoutine(tc)
Важно:

Кто и когда закрывает эту горутину?

2023-05-10 17:45 UTC, dshemin commented on hw11_telnet_client/main.go
> +	wg.Add(1)
Важно:

wg.Add(1) над горутиной которая не делает wg.Done(). Чтобы не запутывать тех, кто будет поддерживать код, так делать не стоит. Размещайте там, где она будет использоваться.

2023-05-10 17:45 UTC, dshemin commented on hw11_telnet_client/main.go
> +	signal.Notify(exitSignal, syscall.SIGINT)
Критично:

Нет обработки Ctrl+D, прочитайте внимательно задание.

2023-05-11 18:16 UTC, filatkinen commented on hw11_telnet_client/main.go
> +	scanner := bufio.NewScanner(os.Stdin)
Здесь все сложно(возможно мне так кажется). Если посмотреть на задание, то по условиям был дан интерфейс 
type TelnetClient interface {
	Connect() error
	io.Closer
	Send() error
	Receive() error
}
и функция
func NewTelnetClient(address string, timeout time.Duration, in io.ReadCloser, out io.Writer) TelnetClient {

т.е. функция возвращает интерфейс, но не структуру, в которой можно указать поле net.Conn и к которому можно было бы  обращаться из программы. Можно конечно использовать type assertion, но это была бы уловка.

т.е. то, что написано продиктовано изначальными условиями задачи. Я могу быть не прав, но другого способа я не нашел.

Если указать входной поток, то мы не сможем обрабатывать  сигналами прерывания. Можем конечно его закрывать, и что-то даже получается, но прерывать программу, не выходит - у нас есть только 4 метода клиента через интерфейсную переменную.

Опять таки в примере обыграно через обертку через канал
https://github.com/OtusGolang/webinars_practical_part/blob/master/24-context-n-net/02-chat-client/client.go

2023-05-11 18:16 UTC, filatkinen commented on hw11_telnet_client/main.go
> +	defer wg.Done()
Дмитрий, я подобные решения видел в качестве материалов к лекциям. Понимаю что зависимость, можно исключить, если использовать неименованную функцию в теле основной рутины. Можно обыграть каналами, но это та же зависимость. 
Вот ссылка на пример: https://github.com/OtusGolang/webinars_practical_part/blob/master/24-context-n-net/02-chat-client/client.go

2023-05-11 18:20 UTC, filatkinen commented on hw11_telnet_client/main.go
> +		receiveRoutine(tc)
Ее не зкрываем, она схлопывается при зкарытии основной. До ее схлопывания зкарывается conn
Опять таки ограничены 4-мя методами через интерфейс. Рутина вешается методом receive на stdin и пока с той стороны не закроется, мы ничего с ней сделать не можем. Ну или через обертку как sender делать, но зачем?

2023-05-11 18:20 UTC, filatkinen commented on hw11_telnet_client/main.go
> +	wg.Add(1)
Да, поправил

2023-05-11 18:27 UTC, filatkinen commented on hw11_telnet_client/main.go
> +	signal.Notify(exitSignal, syscall.SIGINT)
Я не нашел прерывания на conrol+D, перерыл кучу форумов, но это по сути EOF и он у меня обрабатывается, если с консоли ввести контрол D, то scanner закрывается и отрабатывает этот код:
Обработка:  в коде:
	if scanner.Err() == nil {
		fmt.Printf("...EOF")
	}

А в исходниках к scan.go, сказано, что возвращается ошибка, если не только это не EOF
// Scan advances the Scanner to the next token, which will then be
// available through the Bytes or Text method. It returns false when the
// scan stops, either by reaching the end of the input or an error.
// After Scan returns false, the Err method will return any error that
// occurred during scanning, except that if it was io.EOF, Err
// will return nil.  
func (s *Scanner) Scan() bool {

2023-05-12 15:24 UTC, dshemin requested changes

2023-05-12 15:24 UTC, dshemin commented on hw11_telnet_client/main.go
> +	defer wg.Done()
Можно просто wg.Done вынести вне функции и всё :)

2023-05-12 15:24 UTC, dshemin commented on hw11_telnet_client/main.go
> +	scanner := bufio.NewScanner(os.Stdin)
Не понял как интерфейс влияет на то, что мы не можем просто передать stdin. Как не крути, мы его всё равно читаем!

Чтобы прервать программу, нам надо просто вызвать Close на TelnetClient если к нам пришёл сигнал.

2023-05-14 19:10 UTC, dshemin requested changes

2023-05-14 19:10 UTC, dshemin commented on hw11_telnet_client/main.go
> +		fmt.Println("...EOF")
Важно:

Уберите данную строку.

2023-06-17 17:04 UTC, filatkinen commented on hw11_telnet_client/main.go
> +		fmt.Println("...EOF")
Дмитрий, добрый день!
Убрал строку fmt.Println("...EOF")
Также добавил условия выхода из горутин по каналу: одна из 3-ех закрывается и выход из программы. Закрытие клиента по defer.
Туперь по крайней мере Control+C отрабатвает без необходимости нажимания Enter


Локально test.sh отрабатывает, но в гите все тоже.
Почему не знаю.

2023-06-17 18:49 UTC, dshemin requested changes

2023-06-17 18:49 UTC, dshemin commented on hw11_telnet_client/main.go
> +		return
Важно:

Тут мы просто гасим сообщение об ошибке, что если в тестах у нас тут ошибка выскакивает?

2023-06-17 18:49 UTC, dshemin commented on hw11_telnet_client/main.go
> +		return
Важно:

Если ошибка то в main должен быть не return, а os.Exit(1)

2023-06-17 18:49 UTC, dshemin commented on hw11_telnet_client/main.go
> +		return
Важно:

Если ошибка то в main должен быть не return, а os.Exit(1)

2023-06-18 06:29 UTC, filatkinen commented on hw11_telnet_client/main.go
> +		return
Скорректировал

2023-06-18 06:29 UTC, filatkinen commented on hw11_telnet_client/main.go
> +		return
Скорректировал

2023-06-21 17:40 UTC, dshemin approved these changes

2023-06-21 17:55 UTC, merged