HW12 is completed
filatkinen/hw-test pull request #12
Opened 2023-06-17 19:19 UTC by filatkinen

## Домашнее задание №12 «Заготовка сервиса Календарь»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Понятность и чистота кода (включая факт, что проект разбит
на пакеты по определенной логике) - до 2 баллов
- [ ] Реализовано конфигурирование сервиса - 1 балл
- [ ] Используется логгер и он настраивается из конфига - 1 балл
- [ ] Запускается простой HTTP-сервер, мидлвара удовлетворяет ТЗ - 1 балл
- [ ] Присутствуют юнит-тесты - 1 балл

Реализовано хранилище:
- [ ] in-memory - 1 балл
- [ ] sql + миграции - 2 балла

#### Зачёт от 7 баллов

2023-06-18 17:49 UTC, dshemin requested changes

2023-06-18 17:49 UTC, dshemin commented on hw12_13_14_15_calendar/internal/config/server/config.go
> +		duration = DefaultMaxIdleTime
Важно:

Не удачное решение, пользователь так и не узнает что у него не тот таймаут который он хотел. Только потом будет неприятный сюрприз.

2023-06-18 17:49 UTC, dshemin commented on hw12_13_14_15_calendar/internal/config/server/config.go
> +const DefaultMaxIdleTime time.Duration = time.Minute * 15
Важно:

Скорее всего эта константа не должна быть глобальной.

2023-06-18 17:49 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/calendar/calendar.go
> +	servLog.Logging(logger.LevelInfo, "application Calendar started")
Совет:

Громоздко. Интерфейс в виде `log.Info`, `log.Debug` и т.д. более простой и удобный. Да и более привычный.

2023-06-18 17:49 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/models.go
> +func PseudoUUID() string {
Важно:

Этот код скорее всего нужен только в тестах и должен быть туда вынесен.

2023-06-18 17:49 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/models.go
> +		return ""
Важно:

Игнорирование ошибки.

2023-06-18 17:49 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/mysql/storage.go
> +	defer tx.Rollback()
Важно:

Данный код выполнится при завершении функции, Даже если всё было успешно и мы уже сделали commit. Не очень хорошо. Надо запускать только если была ошибка.

2023-06-18 17:49 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/mysql/storage.go
> +	if err != nil {
Важно:

Если не добавлем контекста ошибке то просто `return err`

2023-06-18 17:49 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/pqsql/storage.go
> +	defer tx.Rollback()
Важно:

Тут тоже проблема с роллбеком после комита

2023-06-18 17:49 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/pqsql/storage.go
> +	if err != nil {
Важно:

Просто return err

2023-06-19 19:05 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/config/server/config.go
> +		duration = DefaultMaxIdleTime
Добавил сообщение в консоль

2023-06-19 19:08 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/config/server/config.go
> +const DefaultMaxIdleTime time.Duration = time.Minute * 15
Перенес в функцию NewConfig. Да, более нигде не используется.

2023-06-20 04:49 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/server/calendar/calendar.go
> +	servLog.Logging(logger.LevelInfo, "application Calendar started")
Поправил.

2023-06-20 04:53 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/storage/models.go
> +func PseudoUUID() string {
Это генератор UUID, не в соотвествии со стандартами, а из набора сучайных значений.
Можно гугловскую библиотеку подключить, но зачем в рамках псевдо-задания :)

Ну вобще используется как генератор, просто не в соотвествии со стандартами.
Используется при создании Event

Переназвал UUID

2023-06-20 16:42 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/storage/models.go
> +		return ""
Исправил

2023-06-20 16:43 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/storage/mysql/storage.go
> +	if err != nil {
да, исправил

2023-06-20 16:44 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/storage/pqsql/storage.go
> +	if err != nil {
да, аналогично исправил

2023-06-20 16:57 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/storage/mysql/storage.go
> +	defer tx.Rollback()
Дмитрий, позвольте не согласиться. Это стандратный template от go https://go.dev/doc/database/execute-transactions 
Также на занятии этот момент рассматривали.
Но раз мастер так желает:))), скорректировал
	defer func() {
		if err != nil {
			tx.Rollback()
		}
	}()

2023-06-20 16:57 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/storage/pqsql/storage.go
> +	defer tx.Rollback()
Прокомментировал ранее аналогичному замечанию.

2023-06-21 16:41 UTC, merged