HW13 is completed
filatkinen/hw-test pull request #13
Opened 2023-07-06 19:05 UTC by filatkinen

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-07-07 10:12 UTC, dshemin requested changes

2023-07-07 10:12 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +generate:
Критично:

Внимательно посмотрите на текст задания:

> добавить в Makefile команду `generate`; `make generate` - вызывает `go generate`, которая в свою очередь
генерирует код GRPC сервера на основе Protobuf спецификаций;

2023-07-07 10:12 UTC, dshemin commented on hw12_13_14_15_calendar/internal/grpcservice/server/server.go
> +	return nil
Важно:

Не реализовано, так и должно быть?

2023-07-07 10:12 UTC, dshemin commented on hw12_13_14_15_calendar/internal/grpcservice/server/server.go
> +	return nil
Важно:

Не реализовано, так и должно быть?

2023-07-07 19:26 UTC, filatkinen commented on hw12_13_14_15_calendar/Makefile
> +generate:
Сделал.

2023-07-07 19:27 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/grpcservice/server/server.go
> +	return nil
Осталял на следующее задание - на планировщик, но сделал

2023-07-07 19:27 UTC, filatkinen commented on hw12_13_14_15_calendar/internal/grpcservice/server/server.go
> +	return nil
Осталял на следующее задание - на планировщик, но сделал

2023-07-08 06:03 UTC, dshemin approved these changes

2023-08-22 06:59 UTC, merged